use_default_settings: true

general:
  instance_name: "AI Stack Search"

search:
  safe_search: 0
  autocomplete: "google"

server:
  secret_key: "ultrasecretkey123456789"
  limiter: false
  image_proxy: true

ui:
  static_use_hash: true

enabled_plugins:
  - 'Hash plugin'
  - 'Search on category select'
  - 'Tracker URL remover'

outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0
